/* ============================================================
   雀ドルを探せ — キャラクターデータ（Ver.0.5 / 50人）
   ・追加するときは末尾に足すだけ。既存のidは絶対に変えないこと
   ・セーブデータはidで持つので、順番を入れ替えても壊れない
   ============================================================ */

/* 打ち筋20種。数値はそのままCPU思考の係数になる。
   push     : 押し引きの強さ（高いほど押す）
   call     : 鳴きやすさ
   riichi   : リーチ判断（高いほど積極的にかける）
   defense  : 危険度をどれだけ重く見るか
   speed    : 受け入れ枚数を打点より優先する度合い
   value    : 打点を受け入れより優先する度合い
   variance : ムラ。局ごとに上の係数が揺れる幅
   endgame  : 終盤の条件戦での判断精度                          */
const STYLES = {
  menzen:   { name: '門前高打点型', push: 0.6, call: 0.1, riichi: 0.9, defense: 0.5, speed: 0.3, value: 0.9, variance: 0.2, endgame: 0.5 },
  speed:    { name: '速攻型',       push: 0.6, call: 0.6, riichi: 0.8, defense: 0.4, speed: 0.95, value: 0.2, variance: 0.15, endgame: 0.4 },
  naki:     { name: '鳴き特化型',   push: 0.65, call: 0.95, riichi: 0.5, defense: 0.35, speed: 0.8, value: 0.4, variance: 0.2, endgame: 0.45 },
  wall:     { name: '鉄壁守備型',   push: 0.2, call: 0.3, riichi: 0.5, defense: 0.95, speed: 0.5, value: 0.4, variance: 0.1, endgame: 0.6 },
  balance:  { name: 'バランス型',   push: 0.5, call: 0.5, riichi: 0.7, defense: 0.6, speed: 0.6, value: 0.5, variance: 0.15, endgame: 0.55 },
  oya:      { name: '親番爆発型',   push: 0.75, call: 0.5, riichi: 0.85, defense: 0.4, speed: 0.5, value: 0.7, variance: 0.35, endgame: 0.4 },
  oorasu:   { name: 'オーラス勝負師型', push: 0.55, call: 0.5, riichi: 0.7, defense: 0.55, speed: 0.55, value: 0.6, variance: 0.2, endgame: 0.95 },
  lasukai:  { name: 'ラス回避特化型', push: 0.3, call: 0.4, riichi: 0.55, defense: 0.85, speed: 0.6, value: 0.3, variance: 0.1, endgame: 0.8 },
  top:      { name: 'トップ取り特化型', push: 0.85, call: 0.5, riichi: 0.9, defense: 0.25, speed: 0.5, value: 0.75, variance: 0.3, endgame: 0.7 },
  some:     { name: '染め手嗜好型', push: 0.6, call: 0.7, riichi: 0.6, defense: 0.4, speed: 0.25, value: 0.95, variance: 0.35, endgame: 0.4 },
  toitoi:   { name: '仕掛け重視型', push: 0.7, call: 0.9, riichi: 0.45, defense: 0.35, speed: 0.5, value: 0.8, variance: 0.3, endgame: 0.45 },
  chiitoi:  { name: '変則手型',     push: 0.5, call: 0.15, riichi: 0.75, defense: 0.6, speed: 0.35, value: 0.7, variance: 0.4, endgame: 0.5 },
  judge:    { name: 'リーチ判断職人型', push: 0.55, call: 0.35, riichi: 0.95, defense: 0.7, speed: 0.6, value: 0.6, variance: 0.1, endgame: 0.7 },
  betaori:  { name: 'ベタオリ名人型', push: 0.15, call: 0.35, riichi: 0.5, defense: 1.0, speed: 0.55, value: 0.35, variance: 0.08, endgame: 0.6 },
  shoubu:   { name: '勝負手一点集中型', push: 0.45, call: 0.3, riichi: 0.7, defense: 0.75, speed: 0.35, value: 0.9, variance: 0.25, endgame: 0.6 },
  mura:     { name: 'ムラ型天才',   push: 0.7, call: 0.5, riichi: 0.8, defense: 0.45, speed: 0.6, value: 0.7, variance: 0.6, endgame: 0.5 },
  mental:   { name: 'メンタル連動型', push: 0.6, call: 0.5, riichi: 0.75, defense: 0.5, speed: 0.6, value: 0.55, variance: 0.45, endgame: 0.5 },
  read:     { name: '情報読解型',   push: 0.55, call: 0.45, riichi: 0.75, defense: 0.85, speed: 0.65, value: 0.55, variance: 0.08, endgame: 0.85 },
  gyakkyo:  { name: '逆境型',       push: 0.6, call: 0.5, riichi: 0.7, defense: 0.55, speed: 0.55, value: 0.6, variance: 0.3, endgame: 0.75 },
  perfect:  { name: '完成型オールラウンダー', push: 0.6, call: 0.55, riichi: 0.8, defense: 0.8, speed: 0.7, value: 0.65, variance: 0.05, endgame: 0.9 },
};

const REGIONS = ['北海道・東北', '関東', '中部', '関西', '中国・四国', '九州・沖縄'];

/* 契約難度 */
const CONTRACTS = {
  free:    '即加入',
  cheap:   '低額契約で加入',
  rank:    '事務所ランクが必要',
  money:   'まとまった資金が必要',
  result:  '大会実績が必要',
  pop:     '人気ランキング条件',
  aisho:   '特定の所属雀ドルが必要',
  rival:   'ライバル撃破が条件',
  area:    '地域制覇が条件',
  event:   'イベント完了で加入',
};

/* ------------------------------------------------------------
   雀ドル本体
   atk 攻撃力 / def 守備力 / pop 人気 / pot 伸びしろ（いずれも0-100）
   look はMJ用の外見メモ。画像は img/<id>.webp を読む
------------------------------------------------------------ */
const JANDOLS = [
  // ===== S級 8人（雀エイト） =====
  { id: 1, name: '天城 リオ', kana: 'あまぎ りお', age: 26, region: '関東', rank: 'S',
    style: 'perfect', chara: 'さばさば姉御', sell: '正統派美人', growth: '完成型', contract: 'event',
    atk: 88, def: 90, pop: 92, pot: 5, salary: 480000,
    copy: '雀エイトの中心',
    look: '黒のロングストレート、切れ長の紅い瞳、黒のパンツスーツに白シャツ、細い金のピアス、涼しげな微笑' },
  { id: 2, name: '九条 しおり', kana: 'くじょう しおり', age: 24, region: '関西', rank: 'S',
    style: 'read', chara: '無口だけど熱い', sell: 'クールビューティー', growth: '完成型', contract: 'result',
    atk: 82, def: 95, pop: 61, pot: 8, salary: 400000,
    copy: '卓上を読む氷の瞳',
    look: '銀髪のショートボブ、氷色の瞳、濃紺のベスト、白手袋、無表情' },
  { id: 3, name: '鳳城 かなで', kana: 'ほうじょう かなで', age: 28, region: '関東', rank: 'S',
    style: 'top', chara: '負けず嫌い', sell: 'セクシー系', growth: '完成型', contract: 'money',
    atk: 96, def: 58, pop: 88, pot: 4, salary: 520000,
    copy: '玉砕上等の絶対王者',
    look: '深紅のウェーブロング、金の瞳、黒のロングドレス、赤い羽扇、不敵な笑み' },
  { id: 4, name: '氷室 しのぶ', kana: 'ひむろ しのぶ', age: 31, region: '北海道・東北', rank: 'S',
    style: 'wall', chara: 'クール', sell: '知性派', growth: '完成型', contract: 'rival',
    atk: 62, def: 99, pop: 55, pot: 3, salary: 430000,
    copy: '誰も刺さらない城壁',
    look: '灰青の低いポニーテール、眼鏡、白衣のような長い上着、無駄のない所作' },
  { id: 5, name: '疾風 みお', kana: 'はやて みお', age: 21, region: '九州・沖縄', rank: 'S',
    style: 'speed', chara: '明るい元気娘', sell: 'スポーツ系', growth: '完成型', contract: 'pop',
    atk: 89, def: 66, pop: 90, pot: 12, salary: 390000,
    copy: '誰よりも早く牌に触れる',
    look: '橙のショートヘアにヘアバンド、大きな琥珀の瞳、ジャージ風の上着、日焼けした肌、満面の笑み' },
  { id: 6, name: '白鷺 那月', kana: 'しらさぎ なつき', age: 27, region: '中部', rank: 'S',
    style: 'oorasu', chara: 'お姉さん系', sell: '和風・清楚系', growth: '完成型', contract: 'area',
    atk: 84, def: 80, pop: 86, pot: 5, salary: 460000,
    copy: '最後に笑う逆転姫',
    look: '白銀の長い髪を白い簪でまとめる、薄紫の着物、静かな微笑、細い指' },
  { id: 7, name: '獅子堂 まりあ', kana: 'ししどう まりあ', age: 23, region: '関西', rank: 'S',
    style: 'naki', chara: '小悪魔', sell: 'バラエティ担当', growth: '完成型', contract: 'aisho',
    atk: 91, def: 62, pop: 94, pot: 9, salary: 470000,
    copy: '副露の魔術師',
    look: '金の縦ロール、紫の瞳、派手な赤いジャケット、指輪だらけの手、いたずらっぽい表情' },
  { id: 8, name: '朧 ゆかり', kana: 'おぼろ ゆかり', age: 25, region: '中国・四国', rank: 'S',
    style: 'mura', chara: 'ミステリアス', sell: '個性派', growth: '完成型', contract: 'event',
    atk: 97, def: 40, pop: 79, pot: 15, salary: 350000,
    copy: '当たれば誰も止められない',
    look: '藤色の乱れた長髪、片目を隠す前髪、色違いの瞳、黒いローブ風の上着、気だるげ' },

  // ===== A級 8人 =====
  { id: 9, name: '雪代 朱音', kana: 'ゆきしろ あかね', age: 22, region: '北海道・東北', rank: 'A',
    style: 'lasukai', chara: '真面目委員長', sell: '知性派', growth: '守備特化成長', contract: 'rival',
    atk: 64, def: 88, pop: 58, pot: 30, salary: 210000,
    copy: '沈まない理論派',
    look: '濃紺のセミロングを一つに結ぶ、赤縁の眼鏡、紺のブレザー、几帳面な姿勢' },
  { id: 10, name: '不知火 セナ', kana: 'しらぬい せな', age: 20, region: '九州・沖縄', rank: 'A',
    style: 'top', chara: '小悪魔', sell: 'セクシー系', growth: '爆発成長型', contract: 'money',
    atk: 90, def: 45, pop: 81, pot: 35, salary: 260000,
    copy: '勝つか散るかの炎',
    look: '赤みがかった黒のロング、鋭い八重歯、黒革のジャケット、へそ出し、挑発的な笑み' },
  { id: 11, name: '神代 ミサ', kana: 'かみしろ みさ', age: 23, region: '関東', rank: 'A',
    style: 'menzen', chara: '負けず嫌い', sell: '正統派美人', growth: '攻撃特化成長', contract: 'result',
    atk: 85, def: 60, pop: 74, pot: 28, salary: 230000,
    copy: '一撃の女王候補',
    look: '艶のある黒髪ロング、意志の強い眉、白のブラウスに黒リボン、真剣な眼差し' },
  { id: 12, name: '嵐山 ことね', kana: 'あらしやま ことね', age: 21, region: '関西', rank: 'A',
    style: 'oya', chara: 'ギャル', sell: '個性派', growth: '爆発成長型', contract: 'pop',
    atk: 87, def: 48, pop: 85, pot: 40, salary: 240000,
    copy: '親番、爆ぜます',
    look: '明るい金髪のツインテール、濃いメイク、派手なネイル、ピンクのジャージ、ガムを噛む' },
  { id: 13, name: '桐生 いつき', kana: 'きりゅう いつき', age: 25, region: '中部', rank: 'A',
    style: 'judge', chara: '職人肌', sell: 'クールビューティー', growth: '安定成長型', contract: 'rank',
    atk: 76, def: 82, pop: 52, pot: 22, salary: 220000,
    copy: 'かけるか、伏せるか',
    look: '短く切った黒髪、鋭い目つき、作務衣風の上着、腕を組む立ち姿' },
  { id: 14, name: '大和田 ひなの', kana: 'おおわだ ひなの', age: 27, region: '中国・四国', rank: 'A',
    style: 'toitoi', chara: 'さばさば姉御', sell: 'バラエティ担当', growth: '対局経験で伸びる型', contract: 'cheap',
    atk: 83, def: 55, pop: 70, pot: 25, salary: 190000,
    copy: '鳴いて殴る',
    look: '茶のショートヘア、大柄で姿勢がいい、袖をまくったシャツ、豪快な笑い顔' },
  { id: 15, name: '天ヶ瀬 るり', kana: 'あまがせ るり', age: 21, region: '関東', rank: 'A',
    style: 'chiitoi', chara: '天然', sell: '癒やし系', growth: '晩成型', contract: 'aisho',
    atk: 72, def: 74, pop: 78, pot: 38, salary: 200000,
    copy: '読めないふわふわ',
    look: '水色のゆるふわロング、眠そうな瞳、白のカーディガン、猫のブローチ' },
  { id: 16, name: '真壁 きょうか', kana: 'まかべ きょうか', age: 29, region: '北海道・東北', rank: 'A',
    style: 'gyakkyo', chara: '無口だけど熱い', sell: 'スポーツ系', growth: '大舞台で伸びる型', contract: 'event',
    atk: 80, def: 76, pop: 60, pot: 26, salary: 215000,
    copy: '追い込まれてからが本番',
    look: '黒のベリーショート、額の絆創膏、黒いスポーツウェア、鍛えられた肩' },

  // ===== B級 12人 =====
  { id: 17, name: '三上 ルカ', kana: 'みかみ るか', age: 20, region: '関西', rank: 'B',
    style: 'naki', chara: 'ギャル', sell: 'バラエティ担当', growth: '対局経験で伸びる型', contract: 'pop',
    atk: 74, def: 50, pop: 72, pot: 45, salary: 120000, copy: '卓上の騒音機関車',
    look: '茶髪の巻き髪、大きなイヤリング、ルーズな制服、常に喋っている' },
  { id: 18, name: '白鷺 香澄', kana: 'しらさぎ かすみ', age: 24, region: '中部', rank: 'B',
    style: 'oorasu', chara: 'お姉さん系', sell: '和風・清楚系', growth: '大舞台で伸びる型', contract: 'event',
    atk: 70, def: 72, pop: 68, pot: 40, salary: 130000, copy: '最後に笑う逆転姫（見習い）',
    look: '黒髪をまとめた和装、淡い桜色の帯、伏し目がち、[[白鷺 那月]]の妹' },
  { id: 19, name: '黒峰 レイナ', kana: 'くろみね れいな', age: 22, region: '関東', rank: 'B',
    style: 'wall', chara: 'クール', sell: 'クールビューティー', growth: '安定成長型', contract: 'rank',
    atk: 55, def: 84, pop: 56, pot: 35, salary: 115000, copy: '沈黙のディフェンダー',
    look: '黒のショート、感情の出ない目、黒のタートルネック、細身' },
  { id: 20, name: '花巻 つむぎ', kana: 'はなまき つむぎ', age: 21, region: '北海道・東北', rank: 'B',
    style: 'chiitoi', chara: '天然', sell: '癒やし系', growth: '爆発成長型', contract: 'cheap',
    atk: 66, def: 62, pop: 71, pot: 52, salary: 105000, copy: 'ふわふわ変則派',
    look: '亜麻色のおさげ、そばかす、厚手のニット、ぽかんとした表情' },
  { id: 21, name: '御堂 あさひ', kana: 'みどう あさひ', age: 21, region: '九州・沖縄', rank: 'B',
    style: 'speed', chara: '生意気な後輩', sell: 'スポーツ系', growth: '早熟型', contract: 'free',
    atk: 76, def: 52, pop: 63, pot: 30, salary: 110000, copy: '速さは正義',
    look: '短い赤毛、日焼け、ショートパンツ、いつも走ってきたような息' },
  { id: 22, name: '藤堂 まひる', kana: 'とうどう まひる', age: 26, region: '関西', rank: 'B',
    style: 'menzen', chara: 'お嬢様', sell: '正統派美人', growth: '安定成長型', contract: 'money',
    atk: 78, def: 58, pop: 75, pot: 28, salary: 140000, copy: '育ちのいい一撃',
    look: '栗色の縦ロール、上品なワンピース、扇子、余裕のある笑み' },
  { id: 23, name: '一ノ瀬 ちひろ', kana: 'いちのせ ちひろ', age: 23, region: '中国・四国', rank: 'B',
    style: 'balance', chara: '庶民派努力家', sell: '妹系', growth: '安定成長型', contract: 'free',
    atk: 68, def: 68, pop: 64, pot: 42, salary: 100000, copy: '穴のない小柄',
    look: '茶のショートボブ、小柄、エプロン姿、人懐こい笑顔' },
  { id: 24, name: '土御門 すず', kana: 'つちみかど すず', age: 20, region: '中部', rank: 'B',
    style: 'some', chara: '中二病気質', sell: '個性派', growth: '爆発成長型', contract: 'aisho',
    atk: 79, def: 44, pop: 69, pot: 48, salary: 118000, copy: '一色に染める',
    look: '紫のロングヘアに黒いリボン、包帯を巻いた腕、黒のゴシック服、片目を隠す' },
  { id: 25, name: '宮園 ことは', kana: 'みやぞの ことは', age: 25, region: '関東', rank: 'B',
    style: 'read', chara: '毒舌', sell: '知性派', growth: '晩成型', contract: 'rank',
    atk: 71, def: 79, pop: 54, pot: 33, salary: 125000, copy: '河を見れば分かる',
    look: '黒髪のロング、細い眼鏡、黒のスーツ、腕を組んで見下ろす' },
  { id: 26, name: '砂川 みなみ', kana: 'すながわ みなみ', age: 22, region: '九州・沖縄', rank: 'B',
    style: 'mental', chara: '人見知り', sell: '癒やし系', growth: '人気先行型', contract: 'cheap',
    atk: 73, def: 60, pop: 80, pot: 44, salary: 122000, copy: '波に乗ると止まらない',
    look: '長い黒髪で顔を半分隠す、大きな瞳、ゆったりしたパーカー、おどおど' },
  { id: 27, name: '楠木 えれな', kana: 'くすのき えれな', age: 28, region: '北海道・東北', rank: 'B',
    style: 'betaori', chara: 'おっとり', sell: '和風・清楚系', growth: '守備特化成長', contract: 'free',
    atk: 50, def: 86, pop: 58, pot: 25, salary: 108000, copy: '刺さらないことが仕事',
    look: '灰色がかった髪をゆるくまとめる、和風の割烹着、穏やかな微笑' },
  { id: 28, name: '如月 ひかる', kana: 'きさらぎ ひかる', age: 20, region: '関西', rank: 'B',
    style: 'oya', chara: '負けず嫌い', sell: '妹系', growth: '早熟型', contract: 'result',
    atk: 80, def: 46, pop: 76, pot: 50, salary: 112000, copy: '親が来たら暴れる',
    look: '明るい茶のツインテール、八重歯、赤いジャージ、拳を握る' },

  // ===== C級 14人 =====
  { id: 29, name: '朝倉 ひより', kana: 'あさくら ひより', age: 20, region: '関東', rank: 'C',
    style: 'speed', chara: '明るい元気娘', sell: '妹系', growth: '早熟型', contract: 'free',
    atk: 63, def: 42, pop: 55, pot: 62, salary: 60000, copy: '笑顔で突っ張る超速娘',
    look: 'ピンクがかった茶のショート、大きなリボン、白いセーラー風、飛び跳ねる' },
  { id: 30, name: '南雲 ちさと', kana: 'なぐも ちさと', age: 21, region: '中部', rank: 'C',
    style: 'balance', chara: '真面目委員長', sell: '知性派', growth: '安定成長型', contract: 'free',
    atk: 58, def: 62, pop: 48, pot: 58, salary: 58000, copy: '基本に忠実',
    look: '黒のボブ、太めの眉、紺のカーディガン、背筋が伸びている' },
  { id: 31, name: '古賀 ねね', kana: 'こが ねね', age: 20, region: '九州・沖縄', rank: 'C',
    style: 'naki', chara: '生意気な後輩', sell: 'スポーツ系', growth: '対局経験で伸びる型', contract: 'cheap',
    atk: 64, def: 44, pop: 52, pot: 60, salary: 62000, copy: '鳴いてなんぼ',
    look: '短い黒髪、日焼け、野球帽を後ろ向きに、そばかす' },
  { id: 32, name: '五十嵐 まゆ', kana: 'いがらし まゆ', age: 22, region: '北海道・東北', rank: 'C',
    style: 'wall', chara: 'おっとり', sell: '癒やし系', growth: '守備特化成長', contract: 'free',
    atk: 45, def: 70, pop: 57, pot: 48, salary: 56000, copy: 'まず守る',
    look: '亜麻色のロング、丸眼鏡、厚手のマフラー、のんびりした表情' },
  { id: 33, name: '瀬戸 かんな', kana: 'せと かんな', age: 21, region: '中国・四国', rank: 'C',
    style: 'chiitoi', chara: 'ミステリアス', sell: '個性派', growth: '晩成型', contract: 'cheap',
    atk: 60, def: 58, pop: 61, pot: 55, salary: 64000, copy: '対子しか見えない',
    look: '白髪に近い銀髪のミディアム、無表情、灰色のワンピース、素足' },
  { id: 34, name: '仁科 あおい', kana: 'にしな あおい', age: 23, region: '関西', rank: 'C',
    style: 'lasukai', chara: 'さばさば姉御', sell: 'バラエティ担当', growth: '安定成長型', contract: 'free',
    atk: 52, def: 68, pop: 59, pot: 45, salary: 57000, copy: 'ラスだけは踏まない',
    look: '茶のポニーテール、大きめのTシャツ、腰に手を当てる' },
  { id: 35, name: '柊 みつり', kana: 'ひいらぎ みつり', age: 21, region: '関東', rank: 'C',
    style: 'menzen', chara: '人見知り', sell: '正統派美人', growth: '晩成型', contract: 'aisho',
    atk: 66, def: 50, pop: 66, pot: 63, salary: 66000, copy: '黙って高い手を作る',
    look: '長い黒髪、前髪が長い、白のワンピース、うつむきがち' },
  { id: 36, name: '室伏 のぞみ', kana: 'むろふし のぞみ', age: 24, region: '中部', rank: 'C',
    style: 'toitoi', chara: '職人肌', sell: 'スポーツ系', growth: '攻撃特化成長', contract: 'cheap',
    atk: 67, def: 46, pop: 44, pot: 50, salary: 59000, copy: '対々和しか勝たん',
    look: '刈り上げたショート、太い腕、作業着、無愛想' },
  { id: 37, name: '結城 ゆめ', kana: 'ゆうき ゆめ', age: 20, region: '九州・沖縄', rank: 'C',
    style: 'mental', chara: '天然', sell: '妹系', growth: '人気先行型', contract: 'pop',
    atk: 59, def: 48, pop: 74, pot: 58, salary: 68000, copy: '気分で強さが変わる',
    look: 'ふわふわの桃色の髪、大きな瞳、フリルの多い服、両手を頬に' },
  { id: 38, name: '長谷部 りん', kana: 'はせべ りん', age: 25, region: '北海道・東北', rank: 'C',
    style: 'shoubu', chara: 'クール', sell: '知性派', growth: '安定成長型', contract: 'rank',
    atk: 62, def: 66, pop: 47, pot: 42, salary: 61000, copy: '勝負どころだけ押す',
    look: '黒のショート、細い目、グレーのスーツ、感情を出さない' },
  { id: 39, name: '天羽 さくら', kana: 'あもう さくら', age: 20, region: '関西', rank: 'C',
    style: 'oorasu', chara: '負けず嫌い', sell: '和風・清楚系', growth: '大舞台で伸びる型', contract: 'result',
    atk: 61, def: 60, pop: 65, pot: 57, salary: 63000, copy: '最後の一局に強い',
    look: '桜色の髪を編み込む、袴姿、真剣な目、拳を胸の前で' },
  { id: 40, name: '和泉 みその', kana: 'いずみ みその', age: 27, region: '中国・四国', rank: 'C',
    style: 'some', chara: '毒舌', sell: '個性派', growth: '爆発成長型', contract: 'cheap',
    atk: 65, def: 42, pop: 53, pot: 46, salary: 58000, copy: '一色に賭ける',
    look: '深緑のロングヘア、煙草を模した棒付き飴、だぼだぼの上着、細目' },
  { id: 41, name: '船橋 あき', kana: 'ふなばし あき', age: 22, region: '関東', rank: 'C',
    style: 'gyakkyo', chara: '庶民派努力家', sell: 'スポーツ系', growth: '対局経験で伸びる型', contract: 'free',
    atk: 60, def: 62, pop: 50, pot: 61, salary: 55000, copy: '負けてから伸びる',
    look: '黒のポニーテール、体操着、額に汗、真っ直ぐな目' },
  { id: 42, name: '緋田 ましろ', kana: 'ひだ ましろ', age: 21, region: '中部', rank: 'C',
    style: 'mura', chara: '中二病気質', sell: '個性派', growth: '爆発成長型', contract: 'event',
    atk: 70, def: 38, pop: 62, pot: 66, salary: 67000, copy: '当たれば天才',
    look: '白と黒のメッシュが入った髪、包帯、眼帯、黒いコート' },

  // ===== D級 8人 =====
  { id: 43, name: '玉井 ぽぷり', kana: 'たまい ぽぷり', age: 20, region: '関東', rank: 'D',
    style: 'speed', chara: '明るい元気娘', sell: 'バラエティ担当', growth: '早熟型', contract: 'free',
    atk: 48, def: 32, pop: 58, pot: 74, salary: 32000, copy: '勢いだけはある',
    look: 'オレンジのツインテール、たれ目、ぶかぶかのパーカー、変な帽子' },
  { id: 44, name: '西城 ゆらぎ', kana: 'さいじょう ゆらぎ', age: 21, region: '関西', rank: 'D',
    style: 'mura', chara: '天然', sell: '癒やし系', growth: '爆発成長型', contract: 'free',
    atk: 52, def: 28, pop: 60, pot: 80, salary: 34000, copy: '原石すぎる',
    look: '薄紫の寝癖だらけの髪、眠そうな目、パジャマ風の服、枕を抱える' },
  { id: 45, name: '小鳥遊 ここ', kana: 'たかなし ここ', age: 20, region: '九州・沖縄', rank: 'D',
    style: 'mental', chara: '人見知り', sell: '妹系', growth: '人気先行型', contract: 'free',
    atk: 44, def: 40, pop: 68, pot: 70, salary: 33000, copy: '見た目だけで客が呼べる',
    look: '白に近い金髪のショート、うるんだ瞳、大きなリボン、両手で袖を握る' },
  { id: 46, name: '芦屋 とわ', kana: 'あしや とわ', age: 20, region: '中部', rank: 'D',
    style: 'betaori', chara: 'おっとり', sell: '和風・清楚系', growth: '守備特化成長', contract: 'free',
    atk: 34, def: 56, pop: 51, pot: 62, salary: 30000, copy: '逃げ足だけは一人前',
    look: '黒髪のおかっぱ、細い目、地味な着物、湯呑みを持つ' },
  { id: 47, name: '出雲 なぎさ', kana: 'いずも なぎさ', age: 22, region: '中国・四国', rank: 'D',
    style: 'toitoi', chara: '生意気な後輩', sell: 'スポーツ系', growth: '攻撃特化成長', contract: 'free',
    atk: 50, def: 30, pop: 46, pot: 68, salary: 31000, copy: '鳴きすぎて刺さる',
    look: '短い青髪、日焼け、サーフブランドのシャツ、腕組み' },
  { id: 48, name: '宇佐美 ふゆ', kana: 'うさみ ふゆ', age: 21, region: '北海道・東北', rank: 'D',
    style: 'chiitoi', chara: 'ミステリアス', sell: '個性派', growth: '晩成型', contract: 'free',
    atk: 46, def: 44, pop: 55, pot: 72, salary: 32000, copy: '対子の匂いだけは分かる',
    look: '白銀のロング、雪のような肌、耳当て、無表情、白い息' },
  { id: 49, name: '真鍋 りお', kana: 'まなべ りお', age: 21, region: '関東', rank: 'D',
    style: 'balance', chara: '庶民派努力家', sell: '妹系', growth: '安定成長型', contract: 'free',
    atk: 45, def: 45, pop: 44, pot: 76, salary: 29000, copy: '何でも人並み',
    look: '茶のショート、飾り気のない服、割烹着、はにかんだ笑顔' },
  { id: 50, name: '八雲 みかげ', kana: 'やくも みかげ', age: 23, region: '関西', rank: 'D',
    style: 'gyakkyo', chara: '無口だけど熱い', sell: 'クールビューティー', growth: '晩成型', contract: 'free',
    atk: 47, def: 48, pop: 42, pot: 78, salary: 30000, copy: '這い上がる気だけはある',
    look: '黒のロングを乱雑に結ぶ、目つきが悪い、古いスカジャン、絆創膏' },

  // ===== 追加分（64人トーナメント用・051〜063） =====
  { id: 51, name: '剣持 るい', kana: 'けんもち るい', age: 26, region: '中国・四国', rank: 'A',
    style: 'betaori', chara: '職人肌', sell: '知性派', growth: '守備特化成長', contract: 'rank',
    atk: 68, def: 90, pop: 57, pot: 20, salary: 225000, copy: '刺さらない、それだけ',
    look: '黒髪をきつくまとめた低い団子、細い眉、白シャツにグレーのニットベスト、動かない姿勢' },
  { id: 52, name: '南風原 あかり', kana: 'はえばる あかり', age: 24, region: '九州・沖縄', rank: 'A',
    style: 'some', chara: 'さばさば姉御', sell: 'スポーツ系', growth: '攻撃特化成長', contract: 'pop',
    atk: 86, def: 52, pop: 77, pot: 24, salary: 235000, copy: '染めて殴る島の女',
    look: '日に焼けた肌、色の抜けた茶髪のロング、ゆったりした麻のシャツ、銀のバングル、不敵な笑み' },
  { id: 53, name: '犬飼 まゆら', kana: 'いぬかい まゆら', age: 22, region: '北海道・東北', rank: 'B',
    style: 'judge', chara: '毒舌', sell: '個性派', growth: '安定成長型', contract: 'cheap',
    atk: 72, def: 76, pop: 58, pot: 36, salary: 124000, copy: '言葉より先に牌が出る',
    look: '濃い茶のミディアムに切りそろえた前髪、細い目、大きめのグレーのコート、手をポケットに' },
  { id: 54, name: '神保 ちとせ', kana: 'じんぼう ちとせ', age: 25, region: '関東', rank: 'B',
    style: 'mental', chara: 'お姉さん系', sell: '癒やし系', growth: '大舞台で伸びる型', contract: 'event',
    atk: 75, def: 64, pop: 79, pot: 34, salary: 132000, copy: '波が来たら乗る',
    look: '柔らかい茶のウェーブ、肩までの長さ、温かい笑み、ベージュのカーディガン、小さな真珠のピアス' },
  { id: 55, name: '甲斐 のどか', kana: 'かい のどか', age: 21, region: '中部', rank: 'B',
    style: 'lasukai', chara: '真面目委員長', sell: '知性派', growth: '守備特化成長', contract: 'rank',
    atk: 60, def: 82, pop: 55, pot: 40, salary: 118000, copy: '三着で満足できる強さ',
    look: '黒のストレートにヘアクリップ、細い銀縁の眼鏡、グレーのジャケット、手帳を持つ' },
  { id: 56, name: '名護 ひばり', kana: 'なご ひばり', age: 23, region: '九州・沖縄', rank: 'B',
    style: 'oya', chara: 'ギャル', sell: 'バラエティ担当', growth: '爆発成長型', contract: 'pop',
    atk: 81, def: 50, pop: 73, pot: 38, salary: 128000, copy: '親で全部持っていく',
    look: 'オレンジ寄りに脱色したロング、大きなフープピアス、タンクトップにデニムジャケット、笑っている' },
  { id: 57, name: '芝原 うた', kana: 'しばはら うた', age: 22, region: '中国・四国', rank: 'C',
    style: 'read', chara: '人見知り', sell: '癒やし系', growth: '晩成型', contract: 'free',
    atk: 62, def: 70, pop: 56, pot: 55, salary: 60000, copy: '見てるだけで分かる',
    look: '眉が隠れる前髪の黒髪ロング、大きめのベージュのニット、マグカップを両手で持つ' },
  { id: 58, name: '遠野 きらら', kana: 'とおの きらら', age: 24, region: '北海道・東北', rank: 'C',
    style: 'top', chara: '負けず嫌い', sell: '正統派美人', growth: '攻撃特化成長', contract: 'result',
    atk: 70, def: 45, pop: 64, pot: 50, salary: 65000, copy: '二着は負けと同じ',
    look: '濃い茶の高いポニーテール、強いアイライン、黒のタートルネック、腕を組む' },
  { id: 59, name: '淡路 みちる', kana: 'あわじ みちる', age: 23, region: '関西', rank: 'C',
    style: 'shoubu', chara: 'おっとり', sell: '和風・清楚系', growth: '晩成型', contract: 'cheap',
    atk: 63, def: 66, pop: 58, pot: 52, salary: 61000, copy: 'ここだ、という時だけ',
    look: '栗色の髪をゆるく編む、穏やかな目、灰色の作務衣風の上着' },
  { id: 60, name: '城戸 なずな', kana: 'きど なずな', age: 21, region: '中部', rank: 'C',
    style: 'naki', chara: '生意気な後輩', sell: '妹系', growth: '対局経験で伸びる型', contract: 'free',
    atk: 64, def: 48, pop: 60, pot: 58, salary: 59000, copy: '鳴かなきゃ始まらない',
    look: '短い黒髪に赤いヘアピン、そばかす、大きめのジャージ' },
  { id: 61, name: '保科 ひなた', kana: 'ほしな ひなた', age: 20, region: '関東', rank: 'D',
    style: 'speed', chara: '明るい元気娘', sell: 'スポーツ系', growth: '早熟型', contract: 'free',
    atk: 49, def: 35, pop: 52, pot: 72, salary: 31000, copy: 'とりあえず前に出る',
    look: '茶の短いポニーテール、スポーティなウインドブレーカー、満面の笑み' },
  { id: 62, name: '志摩 うらら', kana: 'しま うらら', age: 22, region: '中国・四国', rank: 'D',
    style: 'read', chara: 'ミステリアス', sell: '個性派', growth: '晩成型', contract: 'free',
    atk: 46, def: 50, pop: 49, pot: 75, salary: 30000, copy: '黙って河を見ている',
    look: '黒のロングヘア、色の白い肌、飾りのない黒いワンピース、無表情' },
  { id: 63, name: '天童 のあ', kana: 'てんどう のあ', age: 21, region: '九州・沖縄', rank: 'D',
    style: 'menzen', chara: '天然', sell: '妹系', growth: '人気先行型', contract: 'free',
    atk: 48, def: 40, pop: 66, pot: 73, salary: 33000, copy: '高い手しか見えない',
    look: '明るい茶のふわっとした肩までの髪、丸い大きな目、淡い色のパーカー' },
];


/* ------------------------------------------------------------
   初期メンバー候補（064〜073）
   事務所を立ち上げたとき、この10人から3人を選んでチームを組む。
   全員フリー・低ランク・伸びしろ大。強さより「役割」が違う
------------------------------------------------------------ */
const FREE_AGENTS = [
  { id: 64, name: '立花 すみれ', kana: 'たちばな すみれ', age: 21, region: '関東', rank: 'D',
    style: 'balance', chara: '真面目委員長', sell: '知性派', growth: '安定成長型', contract: 'free',
    atk: 48, def: 48, pop: 45, pot: 70, salary: 0, comp: 18, copy: '穴を作らないことから',
    look: '黒のセミロングを耳にかける、細い眉、紺のカーディガン、背筋が伸びている' },
  { id: 65, name: '郷田 ゆい', kana: 'ごうだ ゆい', age: 22, region: '中部', rank: 'D',
    style: 'wall', chara: '人見知り', sell: '癒やし系', growth: '守備特化成長', contract: 'free',
    atk: 38, def: 58, pop: 44, pot: 72, salary: 0, comp: 16, copy: 'まず、刺さらないこと',
    look: '暗い茶のロング、前髪が長い、大きめのグレーのパーカー、うつむきがち' },
  { id: 66, name: '早見 かえで', kana: 'はやみ かえで', age: 20, region: '九州・沖縄', rank: 'D',
    style: 'speed', chara: '明るい元気娘', sell: 'スポーツ系', growth: '早熟型', contract: 'free',
    atk: 52, def: 34, pop: 56, pot: 66, salary: 0, comp: 20, copy: '考えるより先に手が動く',
    look: '短い茶髪、日に焼けた肌、赤いスポーツウェア、大きな笑顔' },
  { id: 67, name: '黛 りつ', kana: 'まゆずみ りつ', age: 24, region: '関西', rank: 'D',
    style: 'menzen', chara: 'クール', sell: 'クールビューティー', growth: '晩成型', contract: 'free',
    atk: 50, def: 44, pop: 48, pot: 78, salary: 0, comp: 14, copy: '安い手は打たない',
    look: '黒のストレートロング、細い目、黒のタートルネック、感情を出さない' },
  { id: 68, name: '諏訪 ここね', kana: 'すわ ここね', age: 21, region: '北海道・東北', rank: 'D',
    style: 'naki', chara: 'ギャル', sell: 'バラエティ担当', growth: '対局経験で伸びる型', contract: 'free',
    atk: 51, def: 36, pop: 58, pot: 68, salary: 0, comp: 19, copy: '鳴いて場を回す',
    look: '明るく染めた茶髪の巻き髪、大きなピアス、派手なネイル、ゆるいシャツ' },
  { id: 69, name: '常磐 あやめ', kana: 'ときわ あやめ', age: 23, region: '中国・四国', rank: 'D',
    style: 'read', chara: 'ミステリアス', sell: '個性派', growth: '晩成型', contract: 'free',
    atk: 44, def: 54, pop: 47, pot: 80, salary: 0, comp: 13, copy: '河ばかり見ている',
    look: '黒のロング、色白、黒縁の眼鏡、無地の黒いシャツ、無表情' },
  { id: 70, name: '榊 ひばな', kana: 'さかき ひばな', age: 20, region: '関東', rank: 'D',
    style: 'top', chara: '負けず嫌い', sell: '妹系', growth: '爆発成長型', contract: 'free',
    atk: 56, def: 30, pop: 54, pot: 74, salary: 0, comp: 17, copy: '一番以外に用はない',
    look: '赤みのある茶髪のポニーテール、勝ち気な目、赤いスタジャン、拳を握る' },
  { id: 71, name: '目黒 なぎ', kana: 'めぐろ なぎ', age: 25, region: '中部', rank: 'D',
    style: 'lasukai', chara: 'おっとり', sell: '和風・清楚系', growth: '安定成長型', contract: 'free',
    atk: 40, def: 56, pop: 50, pot: 64, salary: 0, comp: 21, copy: '沈まなければ勝ち',
    look: '亜麻色の髪をゆるくまとめる、穏やかな笑み、生成りのシャツ' },
  { id: 72, name: '相良 とうこ', kana: 'さがら とうこ', age: 22, region: '関西', rank: 'D',
    style: 'chiitoi', chara: '天然', sell: '癒やし系', growth: '爆発成長型', contract: 'free',
    atk: 47, def: 45, pop: 55, pot: 76, salary: 0, comp: 15, copy: '対子が寄ってくる',
    look: '亜麻色のふわっとした髪、ぽかんとした表情、厚手のニット' },
  { id: 73, name: '湊 いおり', kana: 'みなと いおり', age: 24, region: '九州・沖縄', rank: 'D',
    style: 'gyakkyo', chara: '無口だけど熱い', sell: 'スポーツ系', growth: '大舞台で伸びる型', contract: 'free',
    atk: 49, def: 46, pop: 46, pot: 77, salary: 0, comp: 16, copy: '追い込まれてから',
    look: '黒の短髪、鋭い目つき、黒いスポーツジャケット、日焼けした腕' },
];

/* プレイヤー自身。名前と見た目だけ差し替えて使う。
   打ち筋は固定せず、実際の打牌で決まる                          */
const PLAYER = {
  id: 0, name: 'あなた', rank: '—', region: '関東',
  style: null, atk: null, def: null, pop: 40, salary: 0,
};

/* ランクごとの目安（大会の組分けやスカウト難度に使う） */
const RANK_INFO = {
  S: { name: 'S級', label: '雀エイト', scoutCost: 3000000, minAgency: 5 },
  A: { name: 'A級', label: '看板選手', scoutCost: 1200000, minAgency: 4 },
  B: { name: 'B級', label: '主力',     scoutCost: 450000,  minAgency: 2 },
  C: { name: 'C級', label: '発掘層',   scoutCost: 150000,  minAgency: 1 },
  D: { name: 'D級', label: '原石',     scoutCost: 50000,   minAgency: 1 },
};

if (typeof module !== 'undefined') {
  module.exports = { JANDOLS, FREE_AGENTS, PLAYER, STYLES, REGIONS, CONTRACTS, RANK_INFO };
}
